/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package konversibilangan;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class formkonversibilangan extends javax.swing.JFrame {

    /**
     * Creates new form formkonversibilangan
     */
    public formkonversibilangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_data = new javax.swing.JLabel();
        output_data = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bilangan_dari = new javax.swing.JComboBox<>();
        bilangan_ke = new javax.swing.JComboBox<>();
        input_bilangan = new javax.swing.JTextField();
        output_bilangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setText("PROGRAM KONVERSI BILANGAN");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("DARI :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("KE :");

        input_data.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        input_data.setText("INPUT");

        output_data.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        output_data.setText("OUTPUT");

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("CONVERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bilangan_dari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bilangan_dari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hexadecimal", "Decimal", "Biner", "Oktal" }));
        bilangan_dari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilangan_dariActionPerformed(evt);
            }
        });

        bilangan_ke.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bilangan_ke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hexadecimal", "Decimal", "Biner", "Oktal" }));
        bilangan_ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilangan_keActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_data)
                            .addComponent(output_data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(output_bilangan, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(input_bilangan))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(bilangan_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addComponent(bilangan_ke, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(bilangan_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilangan_ke, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_data)
                    .addComponent(input_bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(output_data)
                    .addComponent(output_bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bilangan_dariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilangan_dariActionPerformed
    
        if(bilangan_dari.getSelectedItem() == "Hexadecimal"){
            input_data.setText("INPUT HEXADECIMAL : ");
        }
        if(bilangan_dari.getSelectedItem() == "Decimal"){
            input_data.setText("INPUT DECIMAL : ");
        }
        if(bilangan_dari.getSelectedItem() == "Biner"){
            input_data.setText("INPUT BINER : ");
        }
        if(bilangan_dari.getSelectedItem() == "Oktal"){
            input_data.setText("INPUT OKTAL : ");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bilangan_dariActionPerformed

    private void bilangan_keActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilangan_keActionPerformed
        
        if(bilangan_ke.getSelectedItem() == "Hexadecimal"){
            output_data.setText("OUTPUT HEXADECIMAL : ");
        }
        if(bilangan_ke.getSelectedItem() == "Decimal"){
            output_data.setText("OUTPUT DECIMAL : ");
        }
        if(bilangan_ke.getSelectedItem() == "Biner"){
            output_data.setText("OUTPUT BINER : ");
        }
        if(bilangan_ke.getSelectedItem() == "Oktal"){
            output_data.setText("OUTPUT OKTAL : ");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bilangan_keActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            //konversi bilangan Hexadecimal
            if(bilangan_dari.getSelectedItem() == "Hexadecimal"){
                //konversi hexadecimal ke decimal
                if (bilangan_ke.getSelectedItem() == "Decimal"){
                    String hexa = input_bilangan.getText();
                    int outDes = Integer.parseInt(hexa,16);
                    output_bilangan.setText(Integer.toUnsignedString(outDes));
                }
                //konversi bilangan hexadecimal ke biner
                else if(bilangan_dari.getSelectedItem() == "Biner"){
                    String hexa2 = input_bilangan.getText();
                    int outDes2 = Integer.parseInt(hexa2,16);
                    String hasilDes2 = Integer.toUnsignedString(outDes2);
                    int hasilBiner = Integer.parseInt(hasilDes2);
                    output_bilangan.setText(Integer.toBinaryString(hasilBiner));
                }
                //konversi bilangan Hexadecimal ke Oktal
                else if(bilangan_dari.getSelectedItem() == "Oktal"){
                    String hexa3 = input_bilangan.getText();
                    int outDes3 = Integer.parseInt(hexa3,16);
                    String hasilDes3 = Integer.toUnsignedString(outDes3);
                    int hasilOktal = Integer.parseInt(hasilDes3);
                    output_bilangan.setText(Integer.toOctalString(hasilOktal));
                }
            }
            
            //Konversi bilangan Oktal
            else if(bilangan_dari.getSelectedItem()=="Oktal"){
                //konevrsi Oktal ke Decimal
                if(bilangan_ke.getSelectedItem() == "Decimal"){
                    String oktal4 = input_bilangan.getText();
                    int outDes4 = Integer.parseInt(oktal4,8);
                    output_bilangan.setText(Integer.toUnsignedString(outDes4));
                }
                
                //konversi bilangan Oktal ke Biner
                else if(bilangan_ke.getSelectedItem() == "Biner"){
                    String oktal5 = input_bilangan.getText();
                    int outDes5 = Integer.parseInt(oktal5,8);
                    String hasilDes5 = Integer.toUnsignedString(outDes5);
                    int hasilBiner5 = Integer.parseInt(hasilDes5);
                    output_bilangan.setText(Integer.toBinaryString(hasilBiner5));
                }
                
                //Konversi Oktal ke Hexadecimal
                else if(bilangan_ke.getSelectedItem() == "Hexadecimal"){
                    String oktal6 = input_bilangan.getText();
                    int outDes6 = Integer.parseInt(oktal6,8);
                    String hasilDes6 = Integer.toUnsignedString(outDes6);
                    int hasilHexa6 = Integer.parseInt(hasilDes6);
                    output_bilangan.setText(Integer.toHexString(hasilHexa6));
                } 
            }
            
            //Konversi Bilangan Biner
            else if(bilangan_dari.getSelectedItem()=="Biner"){
                //Konversi Biner ke Decimal
                if(bilangan_ke.getSelectedItem() == "Decimal"){
                    String biner7 = input_bilangan.getText();
                    int outDes7 = Integer.parseInt(biner7,2);
                    output_bilangan.setText(Integer.toUnsignedString(outDes7));
                }
                
                //Konversi Biner ke Oktal
                else if(bilangan_ke.getSelectedItem() == "Oktal"){
                    String biner8 = input_bilangan.getText();
                    int outDes8 = Integer.parseInt(biner8,2);
                    String hasilDes8 = Integer.toUnsignedString(outDes8);
                    int hasilOktal8 = Integer.parseInt(hasilDes8);
                    output_bilangan.setText(Integer.toOctalString(hasilOktal8));
                }
                
                //Konversi Biner ke Hexadecimal
                else if(bilangan_ke.getSelectedItem() == "Hexadecimal"){
                    String biner9 = input_bilangan.getText();
                    int outDes9 = Integer.parseInt(biner9,2);
                    String hasilDes9 = Integer.toUnsignedString(outDes9);
                    int hasilHexa9 = Integer.parseInt(hasilDes9);
                    output_bilangan.setText(Integer.toHexString(hasilHexa9));
                }
            }
            
            //Konversi bilangan Decimal
            else if(bilangan_dari.getSelectedItem()=="Decimal"){
                //Konversi Decimal ke Oktal
                if(bilangan_ke.getSelectedItem() == "Oktal"){
                    String des10 = input_bilangan.getText();
                    int outOktal10 = Integer.parseInt(des10);
                    output_bilangan.setText(Integer.toOctalString(outOktal10));
                }
                
               //Konversi Decimal ke Biner
               if(bilangan_ke.getSelectedItem() == "Biner"){
                    String des11 = input_bilangan.getText();
                    int outBiner11 = Integer.parseInt(des11);
                    output_bilangan.setText(Integer.toBinaryString(outBiner11));
                }
               
               //Konversi Decimal ke Hexadecimal
               if(bilangan_ke.getSelectedItem() == "Hexadecimal"){
                    String des12 = input_bilangan.getText();
                    int outHexa12 = Integer.parseInt(des12);
                    output_bilangan.setText(Integer.toHexString(outHexa12));
                }
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Input Tidak Benar");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formkonversibilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formkonversibilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formkonversibilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formkonversibilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formkonversibilangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bilangan_dari;
    private javax.swing.JComboBox<String> bilangan_ke;
    private javax.swing.JTextField input_bilangan;
    private javax.swing.JLabel input_data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField output_bilangan;
    private javax.swing.JLabel output_data;
    // End of variables declaration//GEN-END:variables
}
